namespace MobileShop.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class m1 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Phones", "General_Type", c => c.String());
            AddColumn("dbo.Phones", "General_OS", c => c.String());
            AddColumn("dbo.Phones", "General_ReleaseDate", c => c.DateTime());
            AddColumn("dbo.Phones", "Processor_ProcessorModel", c => c.String());
            AddColumn("dbo.Phones", "Processor_ProcessorCoreCount", c => c.Int());
            AddColumn("dbo.Phones", "Processor_ProcessorBitWidth", c => c.Int());
            AddColumn("dbo.Phones", "Processor_ProcessorFrequency", c => c.Int());
            AddColumn("dbo.Phones", "Processor_GPUModel", c => c.String());
            AddColumn("dbo.Phones", "Memory_RAM", c => c.Int());
            AddColumn("dbo.Phones", "Memory_MemoryCards", c => c.Boolean());
            AddColumn("dbo.Phones", "Memory_MemoryCardsTypes", c => c.String());
            AddColumn("dbo.Phones", "Memory_InternalMemory", c => c.Int());
            AddColumn("dbo.Phones", "Display_DisplayTechnology", c => c.String());
            AddColumn("dbo.Phones", "Display_DisplayColorsNumber", c => c.Int());
            AddColumn("dbo.Phones", "Display_DisplayDiagonal", c => c.Int());
            AddColumn("dbo.Phones", "Display_DisplayResolution_X", c => c.Int());
            AddColumn("dbo.Phones", "Display_DisplayResolution_Y", c => c.Int());
            AddColumn("dbo.Phones", "Display_DisplayPixelDensity", c => c.Int());
            AddColumn("dbo.Phones", "Display_DisplayTouchscreen", c => c.Boolean());
            AddColumn("dbo.Phones", "Display_DisplayTouchscreenType", c => c.String());
            AddColumn("dbo.Phones", "Display_DisplayTouchscreenMultitouch", c => c.Boolean());
            AddColumn("dbo.Phones", "Display_DisplayProtection", c => c.Boolean());
            AddColumn("dbo.Phones", "Display_DisplayProtectionType", c => c.String());
            AddColumn("dbo.Phones", "Display_DisplayForceSensor", c => c.Boolean());
            AddColumn("dbo.Phones", "Construction_FormFactor", c => c.String());
            AddColumn("dbo.Phones", "Construction_CaseMaterial", c => c.String());
            AddColumn("dbo.Phones", "Construction_StereoSpeakers", c => c.Boolean());
            AddColumn("dbo.Phones", "Construction_WaterDustProtection", c => c.Boolean());
            AddColumn("dbo.Phones", "Construction_WaterDustProtectionType", c => c.String());
            AddColumn("dbo.Phones", "Construction_PhisicalQWERTYKeyboard", c => c.Boolean());
            AddColumn("dbo.Phones", "Construction_SIMCount", c => c.Int());
            AddColumn("dbo.Phones", "Construction_SIMFormat", c => c.String());
            AddColumn("dbo.Phones", "Sensors_Accelerometer", c => c.Boolean());
            AddColumn("dbo.Phones", "Sensors_Gyroscope", c => c.Boolean());
            AddColumn("dbo.Phones", "Sensors_LigthSensor", c => c.Boolean());
            AddColumn("dbo.Phones", "Sensors_FingerPrintSensor", c => c.Boolean());
            AddColumn("dbo.Phones", "Sensors_Barometer", c => c.Boolean());
            AddColumn("dbo.Phones", "DataTransfer_EDGE", c => c.Boolean());
            AddColumn("dbo.Phones", "DataTransfer_HSPA", c => c.Boolean());
            AddColumn("dbo.Phones", "DataTransfer_HSPAPlus", c => c.Boolean());
            AddColumn("dbo.Phones", "DataTransfer_HSUPA", c => c.Boolean());
            AddColumn("dbo.Phones", "DataTransfer_HSDPA", c => c.Boolean());
            AddColumn("dbo.Phones", "DataTransfer_LTE", c => c.Boolean());
            AddColumn("dbo.Phones", "DataTransfer_WiFi", c => c.Boolean());
            AddColumn("dbo.Phones", "DataTransfer_WiFiTypes", c => c.String());
            AddColumn("dbo.Phones", "DataTransfer_Bluetooth", c => c.Boolean());
            AddColumn("dbo.Phones", "DataTransfer_BluetoothVersion", c => c.String());
            AddColumn("dbo.Phones", "DataTransfer_IrDA", c => c.Boolean());
            DropColumn("dbo.Phones", "Type");
            DropColumn("dbo.Phones", "OS");
            DropColumn("dbo.Phones", "ReleaseDate");
            DropColumn("dbo.Phones", "ProcessorModel");
            DropColumn("dbo.Phones", "ProcessorCoreCount");
            DropColumn("dbo.Phones", "ProcessorBitWidth");
            DropColumn("dbo.Phones", "ProcessorFrequency");
            DropColumn("dbo.Phones", "GPUModel");
            DropColumn("dbo.Phones", "RAM");
            DropColumn("dbo.Phones", "MemoryCards");
            DropColumn("dbo.Phones", "MemoryCardsTypes");
            DropColumn("dbo.Phones", "InternalMemory");
            DropColumn("dbo.Phones", "Camera");
            DropColumn("dbo.Phones", "CameraResolution");
            DropColumn("dbo.Phones", "CameraVideoResolution");
            DropColumn("dbo.Phones", "CameraOpticalStabilization");
            DropColumn("dbo.Phones", "SecondaryCamera");
            DropColumn("dbo.Phones", "SecondaryCameraResolution");
            DropColumn("dbo.Phones", "SecondaryCameraVideoResolution");
            DropColumn("dbo.Phones", "Flash");
            DropColumn("dbo.Phones", "FlashType");
            DropColumn("dbo.Phones", "DisplayTechnology");
            DropColumn("dbo.Phones", "DisplayColorsNumber");
            DropColumn("dbo.Phones", "DisplayDiagonal");
            DropColumn("dbo.Phones", "DisplayPixelDensity");
            DropColumn("dbo.Phones", "DisplayTouchscreen");
            DropColumn("dbo.Phones", "DisplayTouchscreenType");
            DropColumn("dbo.Phones", "DisplayTouchscreenMultitouch");
            DropColumn("dbo.Phones", "DisplayProtection");
            DropColumn("dbo.Phones", "DisplayProtectionType");
            DropColumn("dbo.Phones", "DisplayForceSensor");
            DropColumn("dbo.Phones", "FormFactor");
            DropColumn("dbo.Phones", "CaseMaterial");
            DropColumn("dbo.Phones", "StereoSpeakers");
            DropColumn("dbo.Phones", "WaterDustProtection");
            DropColumn("dbo.Phones", "WaterDustProtectionType");
            DropColumn("dbo.Phones", "PhisicalQWERTYKeyboard");
            DropColumn("dbo.Phones", "SIMCount");
            DropColumn("dbo.Phones", "SIMFormat");
            DropColumn("dbo.Phones", "Accelerometer");
            DropColumn("dbo.Phones", "Gyroscope");
            DropColumn("dbo.Phones", "LigthSensor");
            DropColumn("dbo.Phones", "FingerPrintSensor");
            DropColumn("dbo.Phones", "Barometer");
            DropColumn("dbo.Phones", "EDGE");
            DropColumn("dbo.Phones", "HSPA");
            DropColumn("dbo.Phones", "HSPAPlus");
            DropColumn("dbo.Phones", "HSUPA");
            DropColumn("dbo.Phones", "HSDPA");
            DropColumn("dbo.Phones", "LTE");
            DropColumn("dbo.Phones", "WiFi");
            DropColumn("dbo.Phones", "WiFiTypes");
            DropColumn("dbo.Phones", "Bluetooth");
            DropColumn("dbo.Phones", "BluetoothVersion");
            DropColumn("dbo.Phones", "IrDA");
            DropColumn("dbo.Phones", "DisplayResolution_X");
            DropColumn("dbo.Phones", "DisplayResolution_Y");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Phones", "DisplayResolution_Y", c => c.Int());
            AddColumn("dbo.Phones", "DisplayResolution_X", c => c.Int());
            AddColumn("dbo.Phones", "IrDA", c => c.Boolean());
            AddColumn("dbo.Phones", "BluetoothVersion", c => c.String());
            AddColumn("dbo.Phones", "Bluetooth", c => c.Boolean());
            AddColumn("dbo.Phones", "WiFiTypes", c => c.String());
            AddColumn("dbo.Phones", "WiFi", c => c.Boolean());
            AddColumn("dbo.Phones", "LTE", c => c.Boolean());
            AddColumn("dbo.Phones", "HSDPA", c => c.Boolean());
            AddColumn("dbo.Phones", "HSUPA", c => c.Boolean());
            AddColumn("dbo.Phones", "HSPAPlus", c => c.Boolean());
            AddColumn("dbo.Phones", "HSPA", c => c.Boolean());
            AddColumn("dbo.Phones", "EDGE", c => c.Boolean());
            AddColumn("dbo.Phones", "Barometer", c => c.Boolean());
            AddColumn("dbo.Phones", "FingerPrintSensor", c => c.Boolean());
            AddColumn("dbo.Phones", "LigthSensor", c => c.Boolean());
            AddColumn("dbo.Phones", "Gyroscope", c => c.Boolean());
            AddColumn("dbo.Phones", "Accelerometer", c => c.Boolean());
            AddColumn("dbo.Phones", "SIMFormat", c => c.String());
            AddColumn("dbo.Phones", "SIMCount", c => c.Int());
            AddColumn("dbo.Phones", "PhisicalQWERTYKeyboard", c => c.Boolean());
            AddColumn("dbo.Phones", "WaterDustProtectionType", c => c.String());
            AddColumn("dbo.Phones", "WaterDustProtection", c => c.Boolean());
            AddColumn("dbo.Phones", "StereoSpeakers", c => c.Boolean());
            AddColumn("dbo.Phones", "CaseMaterial", c => c.String());
            AddColumn("dbo.Phones", "FormFactor", c => c.String());
            AddColumn("dbo.Phones", "DisplayForceSensor", c => c.Boolean());
            AddColumn("dbo.Phones", "DisplayProtectionType", c => c.String());
            AddColumn("dbo.Phones", "DisplayProtection", c => c.Boolean());
            AddColumn("dbo.Phones", "DisplayTouchscreenMultitouch", c => c.Boolean());
            AddColumn("dbo.Phones", "DisplayTouchscreenType", c => c.String());
            AddColumn("dbo.Phones", "DisplayTouchscreen", c => c.Boolean());
            AddColumn("dbo.Phones", "DisplayPixelDensity", c => c.Int());
            AddColumn("dbo.Phones", "DisplayDiagonal", c => c.Int());
            AddColumn("dbo.Phones", "DisplayColorsNumber", c => c.Int());
            AddColumn("dbo.Phones", "DisplayTechnology", c => c.String());
            AddColumn("dbo.Phones", "FlashType", c => c.String());
            AddColumn("dbo.Phones", "Flash", c => c.Boolean());
            AddColumn("dbo.Phones", "SecondaryCameraVideoResolution", c => c.Int());
            AddColumn("dbo.Phones", "SecondaryCameraResolution", c => c.Int());
            AddColumn("dbo.Phones", "SecondaryCamera", c => c.Boolean());
            AddColumn("dbo.Phones", "CameraOpticalStabilization", c => c.Boolean());
            AddColumn("dbo.Phones", "CameraVideoResolution", c => c.Int());
            AddColumn("dbo.Phones", "CameraResolution", c => c.Int());
            AddColumn("dbo.Phones", "Camera", c => c.Boolean());
            AddColumn("dbo.Phones", "InternalMemory", c => c.Int());
            AddColumn("dbo.Phones", "MemoryCardsTypes", c => c.String());
            AddColumn("dbo.Phones", "MemoryCards", c => c.Boolean());
            AddColumn("dbo.Phones", "RAM", c => c.Int());
            AddColumn("dbo.Phones", "GPUModel", c => c.String());
            AddColumn("dbo.Phones", "ProcessorFrequency", c => c.Int());
            AddColumn("dbo.Phones", "ProcessorBitWidth", c => c.Int());
            AddColumn("dbo.Phones", "ProcessorCoreCount", c => c.Int());
            AddColumn("dbo.Phones", "ProcessorModel", c => c.String());
            AddColumn("dbo.Phones", "ReleaseDate", c => c.DateTime());
            AddColumn("dbo.Phones", "OS", c => c.String());
            AddColumn("dbo.Phones", "Type", c => c.String());
            DropColumn("dbo.Phones", "DataTransfer_IrDA");
            DropColumn("dbo.Phones", "DataTransfer_BluetoothVersion");
            DropColumn("dbo.Phones", "DataTransfer_Bluetooth");
            DropColumn("dbo.Phones", "DataTransfer_WiFiTypes");
            DropColumn("dbo.Phones", "DataTransfer_WiFi");
            DropColumn("dbo.Phones", "DataTransfer_LTE");
            DropColumn("dbo.Phones", "DataTransfer_HSDPA");
            DropColumn("dbo.Phones", "DataTransfer_HSUPA");
            DropColumn("dbo.Phones", "DataTransfer_HSPAPlus");
            DropColumn("dbo.Phones", "DataTransfer_HSPA");
            DropColumn("dbo.Phones", "DataTransfer_EDGE");
            DropColumn("dbo.Phones", "Sensors_Barometer");
            DropColumn("dbo.Phones", "Sensors_FingerPrintSensor");
            DropColumn("dbo.Phones", "Sensors_LigthSensor");
            DropColumn("dbo.Phones", "Sensors_Gyroscope");
            DropColumn("dbo.Phones", "Sensors_Accelerometer");
            DropColumn("dbo.Phones", "Construction_SIMFormat");
            DropColumn("dbo.Phones", "Construction_SIMCount");
            DropColumn("dbo.Phones", "Construction_PhisicalQWERTYKeyboard");
            DropColumn("dbo.Phones", "Construction_WaterDustProtectionType");
            DropColumn("dbo.Phones", "Construction_WaterDustProtection");
            DropColumn("dbo.Phones", "Construction_StereoSpeakers");
            DropColumn("dbo.Phones", "Construction_CaseMaterial");
            DropColumn("dbo.Phones", "Construction_FormFactor");
            DropColumn("dbo.Phones", "Display_DisplayForceSensor");
            DropColumn("dbo.Phones", "Display_DisplayProtectionType");
            DropColumn("dbo.Phones", "Display_DisplayProtection");
            DropColumn("dbo.Phones", "Display_DisplayTouchscreenMultitouch");
            DropColumn("dbo.Phones", "Display_DisplayTouchscreenType");
            DropColumn("dbo.Phones", "Display_DisplayTouchscreen");
            DropColumn("dbo.Phones", "Display_DisplayPixelDensity");
            DropColumn("dbo.Phones", "Display_DisplayResolution_Y");
            DropColumn("dbo.Phones", "Display_DisplayResolution_X");
            DropColumn("dbo.Phones", "Display_DisplayDiagonal");
            DropColumn("dbo.Phones", "Display_DisplayColorsNumber");
            DropColumn("dbo.Phones", "Display_DisplayTechnology");
            DropColumn("dbo.Phones", "Memory_InternalMemory");
            DropColumn("dbo.Phones", "Memory_MemoryCardsTypes");
            DropColumn("dbo.Phones", "Memory_MemoryCards");
            DropColumn("dbo.Phones", "Memory_RAM");
            DropColumn("dbo.Phones", "Processor_GPUModel");
            DropColumn("dbo.Phones", "Processor_ProcessorFrequency");
            DropColumn("dbo.Phones", "Processor_ProcessorBitWidth");
            DropColumn("dbo.Phones", "Processor_ProcessorCoreCount");
            DropColumn("dbo.Phones", "Processor_ProcessorModel");
            DropColumn("dbo.Phones", "General_ReleaseDate");
            DropColumn("dbo.Phones", "General_OS");
            DropColumn("dbo.Phones", "General_Type");
        }
    }
}
